fix the error plzzz
file:///C:/Users/ASUS/Documents/GitHub/Vehicle_Service_Management_System/Backend/Routes/Feedback_Route.js:2
import { Feedback, Feedback } from "../Models/Feedback.js";
                   ^^^^^^^^

SyntaxError: Identifier 'Feedback' has already been declared
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:155:18)
    at callTranslator (node:internal/modules/esm/loader:285:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:30)

Node.js v20.10.0
[nodemon] app crashed - waiting for file changes before
starting...